title: Experience Design in the Open Hybrid Cloud
description: How does if feel currently to experience the Open Hybrid Cloud? What do users see today and how can we design for the future?
author: Liz Blanchard
github: https://github.com/lizsurette
about: I'm a Product Designer working in the Open Hybrid Cloud space.
disqus_shortname:
google_analytics:

enableTags: true
tagarray: []

collections:
  posts:
    output: true
    permalink: /:collection/:path/
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/liz-blanchard-a1365b2/"
    - icon: fa-github
      link: "https://github.com/lizsurette"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Writings
      url: /writings/
    - text: My Projects
      url: /projects/
    - text: Games
      url: /games/

url: "https://lizsurette.github.io"
baseurl: ""

# Pagination
pagination:
  enabled: true
  per_page: 20
  permalink: '/writings/page/:num/'
  title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
