name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build static site
        run: python deploy.py --build

      - name: Fix Sudoku files
        run: |
          mkdir -p _site/static/css
          mkdir -p _site/static/js
          cp -r sudoku/static/css/sudoku.css _site/static/css/
          cp -r sudoku/static/js/sudoku.js _site/static/js/
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          commit_message: 'Deploy static site'
          force: true

      - name: Verify deployment
        run: |
          echo "Deployment completed. Please check https://lizsurette.github.io in a few minutes." 