name: Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: gh-pages

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build static site
        run: python deploy.py --build

      - name: Deploy to GitHub Pages
        run: python deploy.py --deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fix Sudoku files
        run: |
          mkdir -p _site/static/css
          mkdir -p _site/static/js
          if [ -f "sudoku/static/css/sudoku.css" ]; then
            cp -r sudoku/static/css/sudoku.css _site/static/css/
            echo "Copied sudoku.css successfully"
          else
            echo "Warning: sudoku.css not found"
          fi
          if [ -f "sudoku/static/js/sudoku.js" ]; then
            cp -r sudoku/static/js/sudoku.js _site/static/js/
            echo "Copied sudoku.js successfully"
          else
            echo "Warning: sudoku.js not found"
          fi 