name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Deploy to GitHub Pages
        run: |
          # Create a new branch
          git checkout --orphan gh-pages-temp
          
          # Add all files
          git add -A
          
          # Commit changes
          git commit -m "Deploy to GitHub Pages"
          
          # Delete the gh-pages branch if it exists
          git push origin --delete gh-pages || true
          
          # Rename the temporary branch to gh-pages
          git branch -m gh-pages
          
          # Push to GitHub Pages
          git push -f origin gh-pages 