name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install gh-pages
        run: npm install -g gh-pages

      - name: Deploy to GitHub Pages
        run: |
          # Create a temporary directory
          mkdir -p temp_site
          
          # Copy all files except .git and _site
          find . -maxdepth 1 -not -path "*/\.*" -not -path "*/_site" -not -path "*/temp_site" -exec cp -r {} temp_site/ \;
          
          # Copy all directories except .git and _site
          find . -maxdepth 1 -type d -not -path "*/\.*" -not -path "*/_site" -not -path "*/temp_site" -exec cp -r {} temp_site/ \;
          
          # Deploy to GitHub Pages
          gh-pages -d temp_site -t true 