name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install Pygments  # Required for code highlighting

      - name: Create required directories
        run: |
          mkdir -p logs
          mkdir -p app/posts
          mkdir -p build

      - name: Generate static site
        run: |
          python freeze.py
          touch build/.nojekyll  # Prevent GitHub from processing the site with Jekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          force_orphan: true  # Create a new orphan branch for each deployment 